# fly.toml app configuration file generated for link-siee on 2024-10-12T18:01:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'link-siee'
primary_region = 'gig'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'local'
  APP_URL= "https://link-siee.fly.dev"
  APP_DEBUG = 'true'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  DB_CONNECTION = "pgsql"
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="storage_vol"
  destination="/var/www/html/storage"

